version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y ant
  pre_build:
    commands:
      - |
        echo "Nothing to do in the pre_build phase..."
  build: 
    commands:
      - |
        echo Build started on `date`
      - ant javac TIC_hashmap.java
  post_build:
    commands:
      - |
        echo Build completed on `date`
artifacts:
  files:
    - TIC_hashmap.java
  discard-paths: yes
