version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      - |
        echo "Nothing to do in the pre_build phase..."
  build: 
    commands:
      - |
        echo Build started on `date`
      - mvn clean install
        - if [ "$?" -ne 0 ]; then
          - echo "Maven Clean Unsuccessful!"
          - exit 1
        - fi
  post_build:
    commands:
      - dmesg | tail
      - |
        echo Build completed on `date`
artifacts:
  files:
    - TIC_hashmap.java
  discard-paths: yes
